version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "python"
enabled = true
max_line_length = 119

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
